name: Main and Staging Deployment

on:
  push:
    branches:
      - main
      - staging

env:
  AWS_REGION: 'us-east-1'

# Required permissions for OIDC authentication
permissions:
  id-token: write
  contents: read

jobs:
  # Job for deploying to main or staging
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          check-latest: true

      - name: Install project dependencies
        run: |
          npm ci || npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_Branch_Deployment
          aws-region: ${{ env.AWS_REGION }}

      - name: Run deployment script
        id: deploy
        run: |
          # Use the actual branch name for deployment (either "main" or "staging")
          BRANCH_NAME=${{ github.ref_name }}
          chmod +x ./scripts/deploy.sh

          # If branch is main, add the --allow-prod flag
          if [ "$BRANCH_NAME" = "main" ]; then
            ./scripts/deploy.sh --deploy-frontend -e production --allow-prod
          else
            ./scripts/deploy.sh --deploy-frontend -e staging
          fi

          # Log the deployment information
          echo "::notice::Application deployed to $BRANCH_NAME environment"
